#!/bin/bash
set -e

if [ $# -lt 2 ]; then
    echo "usage: $0 <src-dir> <img-tag> [ <s2i-args> ... ]"
    exit 1
fi

fail() {
    echo $1
    exit 1
}

srcdir=$1
shift
[ -d "$srcdir" ] || fail "$srcdir not a directory"
buildtag=$1
shift

origdir=$(pwd)
cd $srcdir
srcdir=$(pwd)

blddir=$(mktemp -d -t s2i-XXXX)
[ -d "$blddir" ] || fail "$blddir not a directory"
docker=$(mktemp -t dockerfile-XXXX)
[ -f "$docker" ] || fail "$docker not a filename"

echo "building in directory $blddir"
cd $blddir

# build using --as-dockerfile, to create an intermediate dockerfile
# that podman can then build
s2i build . "$@" --as-dockerfile $docker

# 'upload/src' appears to be not created in all circumstances,
# so I'll make sure it is here:
mkdir -p upload/src
# the resulting dockerfile expects all src to be staged
# under directory 'upload/src' in the build dir
rm -rf upload/src
cp -r ${srcdir} upload/src

# now that source is staged, we can build with the dockerfile
podman build -t $buildtag -f $docker .

# clean up working files
cd $origdir
rm -rf $blddir $docker
